### ISSUE TITLE
Move over vangaurd optimisations to Illumina data

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#18] opened 2021-06-28 08:36 UTC
I implemented multi-threading in the nanopore version of periscope, this is achieved by splitting the original bam file into parts (how many parts is determined by the user specified amount of threads). These then run in parallel.

```Periscope seems to run slow (a few days using 1 or 2 threads) when there are more than 100 million reads and requires relatively large memory (>64gb). Do you have any suggestion for speeding up the analysis?```

This user has noticed it is pretty slow on very large datasets for Illumina so it would be good to migrate these changes over to the Illumia search functions!

**Comment by mbdabrowska1** [comment] 2021-08-12 09:08
- [x] Merge existing vanguard with current master and resolve conflicts
- [x] Fix vanguard for nanopore data
- [x] Move vanguard optimisation to illumina data
- [x] Fix a bug where more threads create a few more counts for certain ORFs in illumina data (Fixed by implementing multiprocessing on process_reads function, but this does not include processing pairs. Limitation to this solution is the lack of _periscope.bam file being created at the end of periscope.py. This is caused by multiprocessing being unable to deal with pysam object [potential security/incompatibility issues with C])

**Closed as completed** 2021-09-21 09:01 UTC
Labels: enhancement
